name: deploy.yml
on: workflow_dispatch

env:
  DISCORD_ID: ${{ vars.DISCORD_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate HTML
        run: |
          mkdir -p ./build
          envsubst < ./src/template.html > ./build/index.html

      - name: Upload Artefact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
